pipeline:
  republish_image:
    image: docker:18.06
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="regt-build-bot" -p=$${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker pull quay.io/mongodb/charts:19.09
      - docker tag quay.io/mongodb/charts:19.09 docker.digital.homeoffice.gov.uk/evw/mongo-charts:19.09
      - docker push docker.digital.homeoffice.gov.uk/evw/mongo-charts
    when:
      event: push
