pipeline:
  republish_image:
    image: docker:18.06
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="regt-build-bot" -p=$${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker build -t mongo-charts .
      - docker tag mongo-charts docker.digital.homeoffice.gov.uk/evw/mongo-charts:latest
      - docker push docker.digital.homeoffice.gov.uk/evw/mongo-charts
    when:
      event: push
